### ISSUE TITLE
AppiumWebElement.Selected throws exception for UIButton

### ISSUE THREAD

**Issue by h3dkandi** [appium/dotnet-client#185]
## Description

I tried to get a UIButton selected state but it trows an exception

## Environment

* .NET client build version or git revision if you use some shapshot: 3.0.0.2
* Appium server version or git revision if you use some shapshot: v1.6.5-beta (REV a84efcfcbb64f11710058700dc80779b88d84657)
* Desktop OS/version used to run Appium if necessary: macOS 10.12.5 (16F73)
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:  7.4.0
* Mobile platform/version under test: iOS 10.3.1
* Real device or emulator/simulator: real iPhone 6+

## Details

Supposedly partial reproducing steps:
```
var syncButton = driver.FindElementByAccessibilityId("Sync");
var foo = syncButton.Selected;
```

## Ecxeption stacktraces

```
OpenQA.Selenium.WebDriverException was unhandled by user code
  HResult=-2146233088
  Message=Unexpected error. Unhandled endpoint: /session/C7689F70-BB7E-4673-86F6-4D1B17410A70/element/F84E9574-76D5-472A-8EBD-A24EABCFC042/selected -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/C7689F70-BB7E-4673-86F6-4D1B17410A70/element/F84E9574-76D5-472A-8EBD-A24EABCFC042/selected"
    );
}
  Source=WebDriver
  StackTrace:
       at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
       at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Appium.AppiumDriver`1.Execute(String driverCommandToExecute, Dictionary`2 parameters)
       at OpenQA.Selenium.Remote.RemoteWebElement.get_Selected()
       <from here the stack continues to custom code>
  InnerException: 
```
## Link to Appium logs

```
GET /wd/hub/session/f3a7ce90-fe7f-4fa0-b861-4534a696dd12/element/F84E9574-76D5-472A-8EBD-A24EABCFC042/selected {}
2017-07-07 12:21:42:302 - info: [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2017-07-07 12:21:42:303 - info: [debug] [XCUITest] Executing command 'proxyReqRes'
2017-07-07 12:21:42:306 - info: [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/f3a7ce90-fe7f-4fa0-b861-4534a696dd12/element/F84E9574-76D5-472A-8EBD-A24EABCFC042/selected] to [GET http://localhost:8100/session/C7689F70-BB7E-4673-86F6-4D1B17410A70/element/F84E9574-76D5-472A-8EBD-A24EABCFC042/selected] with body: {}
2017-07-07 12:21:42:310 - info: [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Unhandled endpoint: \\/session\\/C7689F70-BB7E-4673-86F6-4D1B17410A70\\/element\\/F84E9574-76D5-472A-8EBD-A24EABCFC042\\/selected -- http:\\/\\/localhost:8100\\/ with parameters {\\n    wildcards =     (\\n        \\\"session\\/C7689F70-BB7E-4673-86F6-4D1B17410A70\\/element\\/F84E9574-76D5-472A-8EBD-A24EABCFC042\\/selected\\\"\\n    );\\n}\",\n  \"sessionId\" : \"C7689F70-BB7E-4673-86F6-4D1B17410A70\",\n  \"status\" : 1\n}"
```

**Comment by dianhua1560** [comment]
Did you resolve this issue?

**Comment by Dor-bl** [comment]
@akinsolb can you have a look on this please? I see it's iOS

**Comment by Dor-bl** [comment]
Closed as no response.
