### ISSUE TITLE
When will there be support for Appium 2.0

### ISSUE THREAD

**Issue by aaronportier** [appium/dotnet-client#524]
## Description

If there is the feature you want to see added to Appium .NET client so please describe necessity of this feature and the way that it should work.
I need the ability to use AppiumBY for The Image Plugins.  Currently I do not see any support for Appium 2.0 via the Dot-net-driver. nor any examples of the Image plugins? Does this already exist for DotNet Driver or is it just not built yet?

**Comment by aaronportier** [comment]
I really want to see an example of Image Plugin with C#. How to do an image based function example and a comparison. I can see them for the other languages but I can not decode them to C#. Any help would be greatly appreciated.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/src/Appium.Net/Appium/AppiumDriver.cs#L197 or https://github.com/appium/appium-dotnet-driver/blob/4570d11267572b861554142d39d4452d853e6118/src/Appium.Net/Appium/AppiumDriver.cs#L597-L683 ?

**Comment by aaronportier** [comment]
Thank you this is very helpful. I do notice Execute does not seem to work
here. One other issue is the comparison actually taking a screenshot where
I am at in the app then matching it against an earlier taken screenshot or
is that a different scenario?

**Comment by Dor-bl** [comment]
@aaronportier we basically added support for appium 2.0 in the latest beta version, can you please check and update if something is missing?

**Comment by grishukov** [comment]
@Dor-bl @KazuCocoa 
 Faced with problem in matching images. Topic looks like i should comment about but i can create new issue if need  
 appium client 5.0 beta 2 , server also latest 2.0.
For example i try basic scenario take Two screenshot of One element and get result that it is the same and matched

So made i something wrong or is it issue? 

run coomand: 

```
node appium server -p 4444 -a 127.0.0.1 -pa /wd/hub --use-plugins images --relaxed-security

[Appium] Attempting to load plugin images...
[debug] [Appium] Requiring plugin at /Users/timur/appiumNode/node_modules/@appium/images-plugin
[Appium] Welcome to Appium v2.0.0-beta.46
[Appium] Non-default server args:
[Appium] {
[Appium]   address: '127.0.0.1',
[Appium]   basePath: '/wd/hub',
[Appium]   port: 4444,
[Appium]   relaxedSecurityEnabled: true,
[Appium]   usePlugins: [
[Appium]     'images'
[Appium]   ]
[Appium] }
```


some code example
```
```           var elem = Driver.FindElement(By.XPath("//android.widget.FrameLayout/android.view.ViewGroup/android.widget.LinearLayout/android.widget.TextView[1]"));
            var scrFile = Convert.ToBase64String(elem.GetScreenshot().AsByteArray);
            var scrFile2 = Convert.ToBase64String(elem.GetScreenshot().AsByteArray);

            var matchOptions = new FeaturesMatchingOptions();
            matchOptions.GoodMatchesFactor = 40;
            matchOptions.MatchFunc = "BRUTE_FORCE_HAMMING";
            matchOptions.DetectorName = "ORB";
            matchOptions.Visualize = true;
            FeaturesMatchingResult result = Driver.MatchImageFeatures(scrFile, scrFile2, matchOptions);
            string countResult =result.TotalCount.ToString();
            result.SaveVisualizationAsFile("outputFile");
            Assert.True(result.TotalCount > 0);
```


I get  "not present in the dictionary." for **totalCount**, actually **outputFile** also not working

```
System.Collections.Generic.KeyNotFoundException: The given key 'totalCount' was not present in the dictionary.

System.Collections.Generic.KeyNotFoundException
The given key 'totalCount' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenQA.Selenium.Appium.ImageComparison.FeaturesMatchingResult.get_TotalCount()
```

serverside log at this moment 
```
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Calling AppiumDriver.compareImages() with args: ["matchFeatures","iVBORw0KGgoAAAANSUhEUgAABAwAAADiCAYAAADK4lWXAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7N1neBTnuTfw/zatem+odwlRhACB6B0DxhQDLuAat8Q+cZw4cTnOm3Ji58QpJ3HsNCcuYMeODQYbjMGAaAZElZAQAhUkJISEJNTbSqvdfT8QiMTuzsyuVrsr6f+7Lj6wc88zjzTzjHbueYosOiXdACIiIiIiIiKiPuSOrgAREREREREROR8mDIiIiIiIiIjICBMGRERERERERGSECQMiIiIiIiIiMsKEAREREREREREZYcKAiIiIiIiIiIwwYUBERERERERERpgwICIiIiIiIiIjTBgQERERERERkREmDIiIiIiIiIjICBMGRERERERERGSECQMiIiIiIiIiMsKEAREREREREREZYcKAiIiIiIiIiIwwYUBERERERERERpgwICIiIiIiIiIjTBgQERERERERkRGloytARERERMOHX0A4/AIj4ebuDaXSBRpNOzSdrairKUVXZ6ujq0dERBZgwoCISEDwqEQsWvGcYMzpo5tRVHDQ5LZ5S59GRMx4s/t2azrw6XvPD6iOg2nuku8gPHqs2e3dmnZs2fiiHWtERM4oMnYCJmTchaj4dLh7+JmNq75SiH/+7Rk71oyIiAaCCQMiIgGubp4Ii0wVjPH0CjC7zT8oCqHhyWa3a7rarK6bPQQERwv+/F2dLXasDQFAWsZyjElfAv/ACMhkcrQ01eDiuQM4fXQz9Hqdo6tHI4yP3ygsXvkDxCRMlhTv7uE7yDUiIiJbYsKAiG5JGjMbHp7+Fu0TGZsGL59gwZjKSzlob2uwqNyG+gpUluVatA/RcLfivp8ieezcfp+5unkhJCwJcUlTsfn9H0Gn63VQ7WikiYgeh1UbXoWbu7fkfQx6/SDWiIiIbI0JAyK6Zers9YJvw60l9obelPNn9zBhQNTHmPTFRsmCviJ...
[AppiumDriver@ff53] Plugins which can handle cmd 'compareImages': images
[AppiumDriver@ff53] Plugin images is now handling cmd 'compareImages'
[AppiumDriver@ff53] Command 'compareImages' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Responding to client with driver.compareImages() result: {"count":0}
[HTTP] <-- POST /wd/hub/session/6ed31803-f2ff-4cd0-98f7-51bdbd190642/appium/compare_images 200 647 ms - 21
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/6ed31803-f2ff-4cd0-98f7-51bdbd190642
[HTTP] {}
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Calling AppiumDriver.deleteSession() with args: ["6ed31803-f2ff-4cd0-98f7-51bdbd190642"]
[AppiumDriver@ff53] Plugins which can handle cmd 'deleteSession': images
[AppiumDriver@ff53] Plugin images is now handling cmd 'deleteSession'
[AppiumDriver@ff53] Executing default handling behavior for command 'deleteSession'
[debug] [AppiumDriver@ff53] Event 'quitSessionRequested' logged at 1667980946154 (13:02:26 GMT+0500 (Uzbekistan Standard Time))
[AppiumDriver@ff53] Removing session 6ed31803-f2ff-4cd0-98f7-51bdbd190642 from our master session list
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Deleting UiAutomator2 session
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Deleting UiAutomator2 server session
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Matched '/' to command name 'deleteSession'
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Proxying [DELETE /] to [DELETE http://127.0.0.1:8203/session/70a69b41-f246-4633-a7da-a86b4ab1d582] with no body
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Got response with status 200: {"sessionId":"70a69b41-f246-4633-a7da-a86b4ab1d582","value":null}
[debug] [ADB] Running '/Users/timur/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[debug] [ADB] Running '/Users/timur/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.infratel.mightycall'
[debug] [Logcat] Stopping logcat capture

```


so is it issue or i made something wrong? Should i create another issue topic?

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium/appium/blob/c43acc23ee80d461747c1912cdcfb136280001a0/packages/images-plugin/lib/compare.js#L42 's behavior, it was maybe different from Appium 1.x's one.

@jlipps Do you remember why https://github.com/appium/appium/blob/c43acc23ee80d461747c1912cdcfb136280001a0/packages/images-plugin/lib/compare.js#L38-L43 returns `{count: 0};` instead of raising an exception like https://github.com/appium/appium-base-driver/blob/b65c3a82863ba5804a318827ba9939dbd09af6a1/lib/basedriver/commands/images.js#L55 did.

**Comment by aaronportier** [comment]
I am seeing additional issues with the current Nugget version 4.3 When it
comes to FindElemenybyImage. I am doing a push pull and appium gives the
wrong coordinates.

**Comment by Dor-bl** [comment]
@aaronportier I'm closing this since the topic of this issue is support for appium 2.x. 
Which we have in the latest beta release. In case you encounter other issues with that version, please open a new issue.
Thank you
