### ISSUE TITLE
[Bug]: same images not match

### ISSUE THREAD

**Issue by grishukov** [appium/dotnet-client#568]
Faced with problem in matching images. Topic looks like i should comment about but i can create new issue if need  
 appium client 5.0 beta 2 , server also latest 2.0.
For example i try basic scenario take Two screenshot of One element and get result that it is the same and matched

So made i something wrong or is it issue? 

run coomand: 

```
node appium server -p 4444 -a 127.0.0.1 -pa /wd/hub --use-plugins images --relaxed-security

[Appium] Attempting to load plugin images...
[debug] [Appium] Requiring plugin at /Users/timur/appiumNode/node_modules/@appium/images-plugin
[Appium] Welcome to Appium v2.0.0-beta.47
[Appium] Non-default server args:
[Appium] {
[Appium]   address: '127.0.0.1',
[Appium]   basePath: '/wd/hub',
[Appium]   port: 4444,
[Appium]   relaxedSecurityEnabled: true,
[Appium]   usePlugins: [
[Appium]     'images'
[Appium]   ]
[Appium] }
```

some code example
```
```           var elem = Driver.FindElement(By.XPath("//android.widget.FrameLayout/android.view.ViewGroup/android.widget.LinearLayout/android.widget.TextView[1]"));
            var scrFile = Convert.ToBase64String(elem.GetScreenshot().AsByteArray);
            var scrFile2 = Convert.ToBase64String(elem.GetScreenshot().AsByteArray);

            var matchOptions = new FeaturesMatchingOptions();
            matchOptions.GoodMatchesFactor = 40;
            matchOptions.MatchFunc = "BRUTE_FORCE_HAMMING";
            matchOptions.DetectorName = "ORB";
            matchOptions.Visualize = true;
            FeaturesMatchingResult result = Driver.MatchImageFeatures(scrFile, scrFile2, matchOptions);
            string countResult =result.TotalCount.ToString();
            result.SaveVisualizationAsFile("outputFile");
            Assert.True(result.TotalCount > 0);
```

I get  "not present in the dictionary." for **totalCount**, actually **outputFile** also not working

```
System.Collections.Generic.KeyNotFoundException: The given key 'totalCount' was not present in the dictionary.

System.Collections.Generic.KeyNotFoundException
The given key 'totalCount' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenQA.Selenium.Appium.ImageComparison.FeaturesMatchingResult.get_TotalCount()
```

serverside log at this moment 
```
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Calling AppiumDriver.compareImages() with args: ["matchFeatures","iVBORw0KGgoAAAANSUhEUgAABAwAAADiCAYAAADK4lWXAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7N1neBTnuTfw/zatem+odwlRhACB6B0DxhQDLuAat8Q+cZw4cTnOm3Ji58QpJ3HsNCcuYMeODQYbjMGAaAZElZAQAhUkJISEJNTbSqvdfT8QiMTuzsyuVrsr6f+7Lj6wc88zjzTzjHbueYosOiXdACIiIiIiIiKiPuSOrgAREREREREROR8mDIiIiIiIiIjICBMGRERERERERGSECQMiIiIiIiIiMsKEAREREREREREZYcKAiIiIiIiIiIwwYUBERERERERERpgwICIiIiIiIiIjTBgQERERERERkREmDIiIiIiIiIjICBMGRERERERERGSECQMiIiIiIiIiMsKEAREREREREREZYcKAiIiIiIiIiIwwYUBERERERERERpgwICIiIiIiIiIjTBgQERERERERkRGloytARERERMOHX0A4/AIj4ebuDaXSBRpNOzSdrairKUVXZ6ujq0dERBZgwoCISEDwqEQsWvGcYMzpo5tRVHDQ5LZ5S59GRMx4s/t2azrw6XvPD6iOg2nuku8gPHqs2e3dmnZs2fiiHWtERM4oMnYCJmTchaj4dLh7+JmNq75SiH/+7Rk71oyIiAaCCQMiIgGubp4Ii0wVjPH0CjC7zT8oCqHhyWa3a7rarK6bPQQERwv+/F2dLXasDQFAWsZyjElfAv/ACMhkcrQ01eDiuQM4fXQz9Hqdo6tHI4yP3ygsXvkDxCRMlhTv7uE7yDUiIiJbYsKAiG5JGjMbHp7+Fu0TGZsGL59gwZjKSzlob2uwqNyG+gpUluVatA/RcLfivp8ieezcfp+5unkhJCwJcUlTsfn9H0Gn63VQ7WikiYgeh1UbXoWbu7fkfQx6/SDWiIiIbI0JAyK6Zers9YJvw60l9obelPNn9zBhQNTHmPTFRsmCviJ...
[AppiumDriver@ff53] Plugins which can handle cmd 'compareImages': images
[AppiumDriver@ff53] Plugin images is now handling cmd 'compareImages'
[AppiumDriver@ff53] Command 'compareImages' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Responding to client with driver.compareImages() result: {"count":0}
[HTTP] <-- POST /wd/hub/session/6ed31803-f2ff-4cd0-98f7-51bdbd190642/appium/compare_images 200 647 ms - 21
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/6ed31803-f2ff-4cd0-98f7-51bdbd190642
[HTTP] {}
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Calling AppiumDriver.deleteSession() with args: ["6ed31803-f2ff-4cd0-98f7-51bdbd190642"]
[AppiumDriver@ff53] Plugins which can handle cmd 'deleteSession': images
[AppiumDriver@ff53] Plugin images is now handling cmd 'deleteSession'
[AppiumDriver@ff53] Executing default handling behavior for command 'deleteSession'
[debug] [AppiumDriver@ff53] Event 'quitSessionRequested' logged at 1667980946154 (13:02:26 GMT+0500 ())
[AppiumDriver@ff53] Removing session 6ed31803-f2ff-4cd0-98f7-51bdbd190642 from our master session list
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Deleting UiAutomator2 session
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Deleting UiAutomator2 server session
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Matched '/' to command name 'deleteSession'
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Proxying [DELETE /] to [DELETE http://127.0.0.1:8203/session/70a69b41-f246-4633-a7da-a86b4ab1d582] with no body
[debug] [AndroidUiautomator2Driver@92d8 (6ed31803)] Got response with status 200: {"sessionId":"70a69b41-f246-4633-a7da-a86b4ab1d582","value":null}
[debug] [ADB] Running '/Users/timur/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[debug] [ADB] Running '/Users/timur/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.infratel.mightycall'
[debug] [Logcat] Stopping logcat capture

```

<img width="812" alt="image" src="https://user-images.githubusercontent.com/50317371/208379639-6429cb6c-f46a-4229-9040-2afb1837be84.png">

**Comment by jlipps** [comment]
it looks like `{count: 0}` is returned when an error occurs in the matching algorithm, presumably because there are no matches. not sure what else to recommend. maybe try with another unrelated image to double check you're using the api correctly? i don't know anything about the dotnet client here.

**Comment by grishukov** [comment]
@jlipps 
You were right. I'm sorry to trouble you. Looks like I tried to decide issue wrong way. 
It turns out it was necessary to use GetImagesSimilarity instead of MatchImageFeatures.
Anyway, thanks for the doubts, it helped)
I'll leave it here as an example
``` csharp     
            var elem = Driver.FindElement(By.XPath(
            "//android.view.ViewGroup/android.widget.LinearLayout/android.widget.Button"));
            var scrFile = Convert.ToBase64String(elem.GetScreenshot().AsByteArray);
            
            Dictionary<object, string> dict = new Dictionary<object, string>();
            dict.Add("command", "cmd uimode night yes");
            Driver.ExecuteScript("mobile:shell", dict);
            Thread.Sleep(3000);
            
            var elem2 = Driver.FindElement(By.XPath(
            "//android.view.ViewGroup/android.widget.LinearLayout/android.widget.Button"));
            var scrFile2 = Convert.ToBase64String(elem2.GetScreenshot().AsByteArray);

           
            var similarityMatching =  new SimilarityMatchingOptions();
            similarityMatching.Visualize = true;
            
            var result = Driver.GetImagesSimilarity(scrFile, scrFile2,similarityMatching);
            string countResult =result.Score.ToString();
            result.SaveVisualizationAsFile("outputFile.jpg");
            Assert.False(result.Score >0.98);
```
<img width="876" alt="image" src="https://user-images.githubusercontent.com/50317371/208873660-8e2a8a0f-63f1-426c-937b-290142ab778a.png">

**Comment by jlipps** [comment]
ah, great!
