### ISSUE TITLE
[Bug]: Unhandled exception. OpenQA.Selenium.Appium.Service.Exceptions.AppiumServerHasNotBeenStartedLocallyException

### ISSUE THREAD

**Issue by Nfactor26** [appium/dotnet-client#584]
## Description

AppiumLocalService -> Start() launches the server as expected. However, in the later half of  Start() , there is a code block to ping the server and wait for a response until timeout. Repeated attempts to ping http://localhost:4723 fails although the appium server is up and running. 
However, if we ping http://localhost:4723/wd/hub by correcting the address , it works as expected. This still doesn't addresses the issue as trying to create a new session fails for the same reason. AppiumCommandExecutor should also be initialized with http://localhost:4723/wd/hub instead of http://localhost:4723.

## Environment

* .NET client build version  : **release/5.0.0.0 branch**
* Appium server version : 1.22.3
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 16.17.0
* Mobile platform/version under test: Android using UIAutomator2 
* Real device or emulator/simulator: emulator

## Code To Reproduce Issue [ Good To Have ]
```
            var appiumOptions = new AppiumOptions()
            {               
                AutomationName = "UIAutomator2",
                DeviceName = "emulator-5554",
                App = "C:\\Users\\Nish2\\Downloads\\ApiDemos-debug.apk"
            };
            appiumOptions.AddAdditionalAppiumOption("appium:platformName", "Android");
            var driver = new AndroidDriver(appiumOptions, TimeSpan.FromSeconds(10));
```

## StackTrace 

```
Unhandled exception. OpenQA.Selenium.Appium.Service.Exceptions.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: "C:\Users\Nish2\AppData\Roaming\npm\node_modules\appium\build\lib\main.js" --port "4723" --address "127.0.0.1".
Time 120000 ms for the service starting has been expired!
   at OpenQA.Selenium.Appium.Service.AppiumLocalService.Start() in E:\Github\dotnet-client\src\Appium.Net\Appium\Service\AppiumLocalService.cs:line 119
   at OpenQA.Selenium.Appium.Service.AppiumCommandExecutor.Execute(Command commandToExecute) in E:\Github\dotnet-client\src\Appium.Net\Appium\Service\AppiumCommandExecutor.cs:line 57
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in E:\Github\dotnet-client\src\Appium.Net\Appium\AppiumDriver.cs:line 92
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(ICommandExecutor commandExecutor, ICapabilities appiumOptions) in E:\Github\dotnet-client\src\Appium.Net\Appium\AppiumDriver.cs:line 41
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(AppiumLocalService service, ICapabilities appiumOptions, TimeSpan commandTimeout) in E:\Github\dotnet-client\src\Appium.Net\Appium\AppiumDriver.cs:line 83
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(ICapabilities appiumOptions, TimeSpan commandTimeout) in E:\Github\dotnet-client\src\Appium.Net\Appium\AppiumDriver.cs:line 53
   at OpenQA.Selenium.Appium.Android.AndroidDriver..ctor(DriverOptions driverOptions, TimeSpan commandTimeout) in E:\Github\dotnet-client\src\Appium.Net\Appium\Android\AndroidDriver.cs:line 61
```

**Comment by Dor-bl** [comment]
Hello @Nfactor26 ,
please note that the .NET client 5.x beta support both Appium server 1.x and 2.x, but since version 1.x is no longer maintained we opted to use the 2.x version which no longer has the wd/hub in the endpoint. 
if you would still like to use Appium server 1.x , you can start it using the below command:
```
# Start the server on the given port, host and use the base path prefix (the default prefix is /)
appium server -pa /wd/hub
```

**Comment by Nfactor26** [comment]
Thanks a lot. I am able to run it by upgrading the appium to 2.x without passing any server parameters. Also, found the new https://appium.github.io/appium/docs/en/2.0/ documentation. I will go through it.

**Comment by Dor-bl** [comment]
Great!
Happy to help, I still need to add some documentation regarding that part in the Readme file I assume, just need to find the time 😁

**Comment by Nfactor26** [comment]
I would love to get involved given I will be spending a lot of time here anyways. I am trying to add support for appium plugin to my open source project [pixel-automation](https://github.com/Nfactor26/pixel-automation) . Please let know if there is a discussion channel on discord or anywhere I can drop in for getting involved. [Contributing on appium](https://appium.github.io/appium/docs/en/2.0/contributing/) guide seems to be missing these information as of now.

**Comment by Dor-bl** [comment]
First of all, we are always happy to get help from contributers.
We are discussing the project at slack, so you can send me your email and I will send you an invite to the channel.
The contribution page you shared is for to the appium server. If you would like to contribute to the .NET client, you will just need to create a fork of the repo, clone it to your local and start pushing PR's to the upstream repo(preferable the 5.0 branch).

**Comment by Nfactor26** [comment]
Please send an invite to Nfactor26@gmail.com
