### ISSUE TITLE
[Feat]: cannot parse capability goog:chromeOptions unrecognized chrome option: AcceptInsecureCertificates

### ISSUE THREAD

**Issue by mdberryh** [appium/dotnet-client#589]
**Is your feature request related to a problem? Please describe.**
Yes, when trying to use chrome on a mobile device the error "unrecognized chrome option" prevents users from automation.

**Describe the solution you'd like**
If the existing ChromeOptions object cannot be used with the mobile instances a "MobileChromeOptions" object is required. Users can't be expected to know that they should use the objects for most situations except when dealing with mobile browsers.

**Describe alternatives you've considered**
The working work around as was mentioned is to create a empty dictionary and pass that into the chrome options. 

**Additional context**

https://github.com/appium/dotnet-client/issues/586

**Comment by Dor-bl** [comment]
@mdberryh I've been running pretty much the same code as you did and had no issues with adding the chromeOptions .
Anything else I'm missing? 

```
var chromeOptions = new ChromeOptions { AcceptInsecureCertificates = true };
            chromeOptions.AddArgument("--log-level=3");
            chromeOptions.AddArgument("--ignore-certificate-errors");

            var capabilities = new AppiumOptions();
            capabilities.DeviceName = "Android Emulator";
            capabilities.PlatformName = "Android";
            capabilities.AutomationName = "UiAutomator2";
            capabilities.App = string.Empty;
           // capabilities.PlatformVersion = "13";
            capabilities.AddAdditionalAppiumOption(AndroidMobileCapabilityType.ChromeOptions, chromeOptions);
            capabilities.AddAdditionalAppiumOption(MobileCapabilityType.NewCommandTimeout, 24 * 60 * 60);
            capabilities.AddAdditionalAppiumOption("wdaStartupRetries", "4");
            capabilities.AddAdditionalAppiumOption("wdaStartupRetryInterval", "20000");

            // Noreset = false removes the app data or cache
            capabilities.AddAdditionalAppiumOption(MobileCapabilityType.NoReset, false);

            // FullReset Uninstalls the App and reinstall every time.
            capabilities.AddAdditionalAppiumOption(MobileCapabilityType.FullReset, false);

            var serverUri = Env.ServerIsRemote() ? AppiumServers.RemoteServerUri : AppiumServers.LocalServiceUri;
            _driver = new AndroidDriver(serverUri, capabilities, Env.ImplicitTimeoutSec);
            _driver.Manage().Timeouts().ImplicitWait = Env.ImplicitTimeoutSec;
```

**Comment by mdberryh** [comment]
Interesting.... I was using the latest beta version of the dotnet appium client, and appium@next (appium2).... I have also tried with the current release with appiumV1.4 and it also had the same issues with parsing the fields, but I was unable to override the older version with the same empty dictionary trick.

I've been working with a few other users, who have the same issue, which is how we got notified of this problem.

As far as what I can add... we use npm to install appium@next, have a running emulator with android v12 on that emulator we have a web app. First we have to get the contexts that are running (to make sure there is a web view) then we change to that context. When we change to the context of the webview is when we see the error.

While typing this... I wonder did you use the code to change the context to the webview that is running on the emulator/device? Just starting appium on android has no issues since it won't use the chrome options until the change to a webview. We have no issues at all with the "Native" context.

**Comment by jlipps** [comment]
@mdberryh if you paste your full appium log it might help. the unknown chrome option might be coming from chromedriver itself?

**Comment by Dor-bl** [comment]
@mdberryh can you share the full log as requested?

**Comment by mdberryh** [comment]
The full log can be found in the linked ticket, but here is the link to the log file from that [https://github.com/appium/dotnet-client/files/10686910/appiumserverlogs_error.log](https://github.com/appium/dotnet-client/files/10686910/appiumserverlogs_error.log)

**Comment by Dor-bl** [comment]
Are you sure your correct emulator is up and running?
`Encountered internal error running command: Error: Unable to find an active device or emulator with OS 11. The following are available: emulator-5554 (12)`

**Comment by mdberryh** [comment]
yup... the hack to create my own dictionary works just fine. The issue is specifically when trying to use the default chrome options object. Could the default code work on all android phones and the issue is my emulator was of a vehicle's android? They all have chrome on them. Maybe a car version of android's chrome is different enough that the fields aren't the same?

**Comment by Dor-bl** [comment]
Never tested an Android car device. So I can't tell 😕

**Comment by mdberryh** [comment]
yeah... this would be the trickiest part to troubleshooting apparently. They normally work just like phones. We use appium and adb for testing all of the time. In this specific instance someone wanted to use web apps on the device. This is why they needed the chrome part. Using our own custom dictionary to pass to chrome we could get our code to function just fine with the web apps. I am surprised the parameters chrome accepts from a phone is different than the car's chrome when both are android.

**Comment by Dor-bl** [comment]
@mdberryh can we close this issue? Or do you have other concerns?

**Comment by mdberryh** [comment]
Well it's not fixed, but we also aren't using the code at this point. I'd say it's up to how you'd like to manage issues. Seems most teams have decided to no longer use C# and rely on python versions instead.

**Comment by Dor-bl** [comment]
if it works for you on python maybe @KazuCocoa can help understand what we do wrong on the dotnet client

**Comment by KazuCocoa** [comment]
I guess `goog:chromeOptions` had invalid keys/values as chromeOptions.
For example, according to the attached log, `"AcceptInsecureCertificates": true,` in `goog:chromeOptions` is invalid. It should not be there. If the `AcceptInsecureCertificates` meant `acceptInsecureCerts`, it should be outside `chromeOptions`.

I'm not sure this is dotnet client issue, but maybe this issue is bad given `goog:chromeOptions` value.

for appium
```
2023-02-08 14:49:55:155 [AndroidUiautomator2Driver@6bea] Creating session with W3C capabilities: {
2023-02-08 14:49:55:156 [AndroidUiautomator2Driver@6bea]   "alwaysMatch": {
2023-02-08 14:49:55:157 [AndroidUiautomator2Driver@6bea]     "platformName": "Android",
2023-02-08 14:49:55:157 [AndroidUiautomator2Driver@6bea]     "goog:chromeOptions": {
2023-02-08 14:49:55:158 [AndroidUiautomator2Driver@6bea]       "CapabilityName": "goog:chromeOptions",
2023-02-08 14:49:55:160 [AndroidUiautomator2Driver@6bea]       "BinaryLocation": null,
2023-02-08 14:49:55:161 [AndroidUiautomator2Driver@6bea]       "LeaveBrowserRunning": false,
2023-02-08 14:49:55:162 [AndroidUiautomator2Driver@6bea]       "Arguments": [
2023-02-08 14:49:55:163 [AndroidUiautomator2Driver@6bea]         "--log-level=3",
2023-02-08 14:49:55:164 [AndroidUiautomator2Driver@6bea]         "--ignore-certificate-errors",
2023-02-08 14:49:55:165 [AndroidUiautomator2Driver@6bea]         "--headless"
2023-02-08 14:49:55:166 [AndroidUiautomator2Driver@6bea]       ],
2023-02-08 14:49:55:167 [AndroidUiautomator2Driver@6bea]       "Extensions": [],
2023-02-08 14:49:55:168 [AndroidUiautomator2Driver@6bea]       "DebuggerAddress": null,
2023-02-08 14:49:55:169 [AndroidUiautomator2Driver@6bea]       "MinidumpPath": null,
2023-02-08 14:49:55:171 [AndroidUiautomator2Driver@6bea]       "PerformanceLoggingPreferences": null,
2023-02-08 14:49:55:173 [AndroidUiautomator2Driver@6bea]       "AndroidOptions": null,
2023-02-08 14:49:55:173 [AndroidUiautomator2Driver@6bea]       "UseSpecCompliantProtocol": true,
2023-02-08 14:49:55:174 [AndroidUiautomator2Driver@6bea]       "BrowserName": "chrome",
2023-02-08 14:49:55:175 [AndroidUiautomator2Driver@6bea]       "BrowserVersion": null,
2023-02-08 14:49:55:175 [AndroidUiautomator2Driver@6bea]       "PlatformName": null,
2023-02-08 14:49:55:176 [AndroidUiautomator2Driver@6bea]       "AcceptInsecureCertificates": true,
2023-02-08 14:49:55:177 [AndroidUiautomator2Driver@6bea]       "UseWebSocketUrl": null,
2023-02-08 14:49:55:178 [AndroidUiautomator2Driver@6bea]       "UnhandledPromptBehavior": 0,
2023-02-08 14:49:55:180 [AndroidUiautomator2Driver@6bea]       "PageLoadStrategy": 0,
2023-02-08 14:49:55:182 [AndroidUiautomator2Driver@6bea]       "Proxy": null,
2023-02-08 14:49:55:183 [AndroidUiautomator2Driver@6bea]       "UseStrictFileInteractability": false
2023-02-08 14:49:55:184 [AndroidUiautomator2Driver@6bea]     },
2023-02-08 14:49:55:185 [AndroidUiautomator2Driver@6bea]     "appium:automationName": "UiAutomator2",
2023-02-08 14:49:55:185 [AndroidUiautomator2Driver@6bea]     "appium:deviceName": "emulator-5554",
2023-02-08 14:49:55:187 [AndroidUiautomator2Driver@6bea]     "appium:platformVersion": "11",
2023-02-08 14:49:55:189 [AndroidUiautomator2Driver@6bea]     "appium:newCommandTimeout": 86400,
2023-02-08 14:49:55:190 [AndroidUiautomator2Driver@6bea]     "appium:wdaStartupRetries": "4",
2023-02-08 14:49:55:190 [AndroidUiautomator2Driver@6bea]     "appium:wdaStartupRetryInterval": "20000",
2023-02-08 14:49:55:191 [AndroidUiautomator2Driver@6bea]     "appium:noReset": false,
2023-02-08 14:49:55:192 [AndroidUiautomator2Driver@6bea]     "appium:fullReset": false
2023-02-08 14:49:55:192 [AndroidUiautomator2Driver@6bea]   },
2023-02-08 14:49:55:195 [AndroidUiautomator2Driver@6bea]   "firstMatch": [
2023-02-08 14:49:55:197 [AndroidUiautomator2Driver@6bea]     {}
2023-02-08 14:49:55:197 [AndroidUiautomator2Driver@6bea]   ]
2023-02-08 14:49:55:198 [AndroidUiautomator2Driver@6bea] }
```

for the chromedriver in a session
```
NT","version":"10.0.19044"},"ready":true}}
2023-02-08 14:55:16:945 [Chromedriver@2db0] Starting W3C Chromedriver session with capabilities: {
2023-02-08 14:55:16:946 [Chromedriver@2db0]   "capabilities": {
2023-02-08 14:55:16:947 [Chromedriver@2db0]     "alwaysMatch": {
2023-02-08 14:55:16:949 [Chromedriver@2db0]       "goog:chromeOptions": {
2023-02-08 14:55:16:950 [Chromedriver@2db0]         "androidPackage": "com.TEST.arcade",
2023-02-08 14:55:16:950 [Chromedriver@2db0]         "androidUseRunningApp": true,
2023-02-08 14:55:16:951 [Chromedriver@2db0]         "androidProcess": "com.TEST.arcade",
2023-02-08 14:55:16:952 [Chromedriver@2db0]         "androidDeviceSerial": "emulator-5554",
2023-02-08 14:55:16:952 [Chromedriver@2db0]         "CapabilityName": "goog:chromeOptions",
2023-02-08 14:55:16:953 [Chromedriver@2db0]         "BinaryLocation": null,
2023-02-08 14:55:16:953 [Chromedriver@2db0]         "LeaveBrowserRunning": false,
2023-02-08 14:55:16:954 [Chromedriver@2db0]         "Extensions": [],
2023-02-08 14:55:16:955 [Chromedriver@2db0]         "DebuggerAddress": null,
2023-02-08 14:55:16:955 [Chromedriver@2db0]         "MinidumpPath": null,
2023-02-08 14:55:16:956 [Chromedriver@2db0]         "PerformanceLoggingPreferences": null,
2023-02-08 14:55:16:956 [Chromedriver@2db0]         "AndroidOptions": null,
2023-02-08 14:55:16:957 [Chromedriver@2db0]         "UseSpecCompliantProtocol": true,
2023-02-08 14:55:16:960 [Chromedriver@2db0]         "BrowserName": "chrome",
2023-02-08 14:55:16:962 [Chromedriver@2db0]         "BrowserVersion": null,
2023-02-08 14:55:16:962 [Chromedriver@2db0]         "PlatformName": null,
2023-02-08 14:55:16:963 [Chromedriver@2db0]         "AcceptInsecureCertificates": true,
2023-02-08 14:55:16:964 [Chromedriver@2db0]         "UseWebSocketUrl": null,
2023-02-08 14:55:16:965 [Chromedriver@2db0]         "UnhandledPromptBehavior": 0,
2023-02-08 14:55:16:965 [Chromedriver@2db0]         "PageLoadStrategy": 0,
2023-02-08 14:55:16:966 [Chromedriver@2db0]         "Proxy": null,
2023-02-08 14:55:16:967 [Chromedriver@2db0]         "UseStrictFileInteractability": false,
2023-02-08 14:55:16:967 [Chromedriver@2db0]         "args": [
2023-02-08 14:55:16:968 [Chromedriver@2db0]           "--log-level=3",
2023-02-08 14:55:16:969 [Chromedriver@2db0]           "--ignore-certificate-errors",
2023-02-08 14:55:16:971 [Chromedriver@2db0]           "--headless"
2023-02-08 14:55:16:972 [Chromedriver@2db0]         ]
2023-02-08 14:55:16:973 [Chromedriver@2db0]       },
2023-02-08 14:55:16:973 [Chromedriver@2db0]       "goog:loggingPrefs": {
2023-02-08 14:55:16:974 [Chromedriver@2db0]         "browser": "ALL"
2023-02-08 14:55:16:975 [Chromedriver@2db0]       }
2023-02-08 14:55:16:976 [Chromedriver@2db0]     }
2023-02-08 14:55:16:976 [Chromedriver@2db0]   }
2023-02-08 14:55:16:977 [Chromedriver@2db0] }
2023-02-08 14:55:16:977 [Chromedriver@2db0] Matched '/session' to command name 'createSession'
2023-02-08 14:55:16:978 [Chromedriver@2db0] Proxying [POST /session] to [POST http://127.0.0.1:8000/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"androidPackage":"com.TEST.arcade","androidUseRunningApp":true,"androidProcess":"com.TEST.arcade","androidDeviceSerial":"emulator-5554","CapabilityName":"goog:chromeOptions","BinaryLocation":null,"LeaveBrowserRunning":false,"Extensions":[],"DebuggerAddress":null,"MinidumpPath":null,"PerformanceLoggingPreferences":null,"AndroidOptions":null,"UseSpecCompliantProtocol":true,"BrowserName":"chrome","BrowserVersion":null,"PlatformName":null,"AcceptInsecureCertificates":true,"UseWebSocketUrl":null,"UnhandledPromptBehavior":0,"PageLoadStrategy":0,"Proxy":null,"UseStrictFileInteractability":false,"args":["--log-level=3","--ignore-certificate-errors","--headless"]},"goog:loggingPrefs":{"browser":"ALL"}}}}
2023-02-08 14:55:17:085 [Chromedriver@2db0] Got response with status 400: {"value":{"error":"invalid argument","message":"invalid argument: cannot parse capability: goog:chromeOptions\nfrom invalid argument: unrecognized chrome option: AcceptInsecureCertificates","stacktrace":"Backtrace:\n\tOrdinal0 [0x01070C43+2493507]\n\tOrdinal0 [0x0100A4B1+2073777]\n\tOrdinal0 [0x00F12608+1058312]\n\tOrdinal0 [0x00F26DC8+1142216]\n\tOrdinal0 [0x00F29674+1152628]\n\tOrdinal0 [0x00F23974+1128820]\n\tOrdinal0 [0x00F58DC4+1347012]\n\tOrdinal0 [0x00F58A1C+1346076]\n\tOrdinal0 [0x00F59CF5+1350901]\n\tOrdinal0 [0x00F59B7A+1350522]\n\tOrdinal0 [0x00F5580B+1333259]\n\tOrdinal0 [0x00F32314+1188628]\n\tOrdinal0 [0x00F3316F+1192303]\n\tGetHandleVerifier [0x011F7BF6+1548950]\n\tGetHandleVerifier [0x012A461C+2256060]\n\tGetHandleVerifier [0x010FC13B+518107]\n\tGetHandleVerifier [0x010FB1E0+514176]\n\tOrdinal0 [0x0100F53D+2094397]\n\tOrdinal0 [0x01013418+2110488]\n\tOrdinal0 [0x01013552+2110802]\n\tOrdinal0 [0x0101CE81+2150017]\n\tBaseThreadInitThunk [0x758200F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x...
2023-02-08 14:55:17:087 [W3C] Matched W3C error code 'invalid argument' to InvalidArgumentError
2023-02-08 14:55:17:122 [Chromedriver@2db0] InvalidArgumentError: invalid argument: cannot parse capability: goog:chromeOptions
2023-02-08 14:55:17:124 [Chromedriver@2db0] from invalid argument: unrecognized chrome option: AcceptInsecureCertificates
2023-02-08 14:55:17:124 [Chromedriver@2db0]     at errorFromW3CJsonCode (C:\Users\happyme\source\GVA\Aurora\AuroraFF\bin\Release\Plugins\MobileTest\ExternalLibs\npm\node_modules\appium-uiautomator2-driver\node_modules\@appium\base-driver\lib\protocol\errors.js:1034:25)
2023-02-08 14:55:17:125 [Chromedriver@2db0]     at ProxyRequestError.getActualError (C:\Users\happyme\source\GVA\Aurora\AuroraFF\bin\Release\Plugins\MobileTest\ExternalLibs\npm\node_modules\appium-uiautomator2-driver\node_modules\@appium\base-driver\lib\protocol\errors.js:909:14)
2023-02-08 14:55:17:126 [Chromedriver@2db0]     at JWProxy.command (C:\Users\happyme\source\GVA\Aurora\AuroraFF\bin\Release\Plugins\MobileTest\ExternalLibs\npm\node_modules\appium-uiautomator2-driver\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:340:19)
2023-02-08 14:55:17:127 [Chromedriver@2db0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-02-08 14:55:17:127 [Chromedriver@2db0]     at Chromedriver.startSession (C:\Users\happyme\source\GVA\Aurora\AuroraFF\bin\Release\Plugins\MobileTest\ExternalLibs\npm\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\chromedriver.js:597:5)
2023-02-08 14:55:17:128 [Chromedriver@2db0]     at Chromedriver.start (C:\Users\happyme\source\GVA\Aurora\AuroraFF\bin\Release\Plugins\MobileTest\ExternalLibs\npm\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\chromedriver.js:528:7)
2023-02-08 14:55:17:129 [Chromedriver@2db0]     at AndroidUiautomator2Driver.setupNewChromedriver (C:\Users\happyme\source\GVA\Aurora\AuroraFF\bin\Release\Plugins\MobileTest\ExternalLibs\npm\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context.js:471:3)
2023-02-08 14:55:17:130 [Chromedriver@2db0]     at AndroidUiautomator2Driver.startChromedriverProxy (C:\Users\happyme\source\GVA\Aurora\AuroraFF\bin\Release\Plugins\MobileTest\ExternalLibs\npm\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context.js:217:10)
2023-02-08 14:55:17:131 [Chromedriver@2db0]     at AndroidUiautomator2Driver.switchContext (C:\Users\happyme\source\GVA\Aurora\AuroraFF\bin\Release\Plugins\MobileTest\ExternalLibs\npm\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context.js:124:5)
2023-02-08 14:55:17:132 [Chromedriver@2db0]     at AndroidUiautomator2Driver.setContext (C:\Users\happyme\source\GVA\Aurora\AuroraFF\bin\Release\Plugins\MobileTest\ExternalLibs\npm\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context.js:51:3)
2023-02-08 14:55:17:141 [Chromedriver@2db0] Chromedriver exited unexpectedly with code null, signal SIGTERM
2023-02-08 14:55:17:142 [Chromedriver@2db0] Changed state to 'stopped'
```

**Comment by Dor-bl** [comment]
@mdberryh, have you had the chance to try to change the caps you are passing according to the latest message?

**Comment by Dor-bl** [comment]
Closing as no response.
