### ISSUE TITLE
[Appium.WebDriver.5.0.0-rc.5]: Toggle wifi functionality not working/ "setConnectivity" "getConnectivity" not supported in .net client even though you could execute via appium inspector

### ISSUE THREAD

**Issue by HarshdeepSingh3009** [appium/dotnet-client#745]
## Description

**Unable to toggle wifi  using AndroidDriver.ToggleWifi() in rc 5. Did not try with previous versions.  Also, I can disable, enable wifi  using appium inspector execute command script but .net client does not allow using the command.**

In appium inspector, one could use mobile: setConnectivity to set wifi status but if I use rc5 .net client, it throws following exception 

Unknown mobile command "setConnectivity". Only shell,execEmuConsoleCommand,dragGesture,flingGesture,doubleClickGesture,clickGesture,longClickGesture,pinchCloseGesture,pinchOpenGesture,swipeGesture,scrollGesture,scrollBackTo,scroll,viewportScreenshot,viewportRect,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,getDeviceTime,changePermissions,getPermissions,performEditorAction,startScreenStreaming,stopScreenStreaming,getNotifications,listSms,type,sensorSet,pushFile,pullFile,pullFolder,deleteFile,isAppInstalled,queryAppState,activateApp,removeApp,terminateApp,installApp,clearApp,startActivity,startService,stopService,broadcast,getContexts,installMultipleApks,unlock,refreshGpsCache,startMediaProjectionRecording,isMediaProjectionRecordingRunning,stopMediaProjectionRecording commands are supported.

Could you add support for this string ? I think if I can do this via appium inspector I should be able to do it via code as well.

## Environment

* .NET client build version or git revision if you use some snapshot:  **5.0.0.-rc.5**
* Appium server version or git revision if you use some snapshot: **2.5.1**
* Desktop OS/version used to run Appium if necessary:
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:  **20.11.1**
* Mobile platform/version under test: **Android 14.0**
* Real device or emulator/simulator: **real device**

## Details

Please provide more details, if necessary.

When I use AndroidDriver.ToggleWifi, it doe snot do anything, No exception is thrown but it does not toggle the wifi as well.

## Exception stack traces

System.NotImplementedException
  HResult=0x80004001
  Message=Unknown mobile command "setConnectivity". Only shell,execEmuConsoleCommand,dragGesture,flingGesture,doubleClickGesture,clickGesture,longClickGesture,pinchCloseGesture,pinchOpenGesture,swipeGesture,scrollGesture,scrollBackTo,scroll,viewportScreenshot,viewportRect,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,getDeviceTime,changePermissions,getPermissions,performEditorAction,startScreenStreaming,stopScreenStreaming,getNotifications,listSms,type,sensorSet,pushFile,pullFile,pullFolder,deleteFile,isAppInstalled,queryAppState,activateApp,removeApp,terminateApp,installApp,clearApp,startActivity,startService,stopService,broadcast,getContexts,installMultipleApks,unlock,refreshGpsCache,startMediaProjectionRecording,isMediaProjectionRecordingRunning,stopMediaProjectionRecording commands are supported.
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.WebDriver.ExecuteScript(String script, Object[] args)

## Link to Appium logs

Please create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs as linked gists! It helps to define the problem correctly and clearly.

**Comment by jlipps** [comment]
Are you sure this message is from the client and not the server? If you link to your Appium logs it will be more clear.

**Comment by HarshdeepSingh3009** [comment]
2024-02-29 02:48:36:425 [AndroidUiautomator2Driver@6a5b (415b5b17)] Command 'toggleWiFi' has been deprecated and will be removed in a future version of Appium or your driver/plugin. Please use a different method or contact the driver/plugin author to add explicit support for the command before it is removed
2024-02-29 02:48:36:425 [AndroidUiautomator2Driver@6a5b (415b5b17)] Calling AppiumDriver.toggleWiFi() with args: ["415b5b17-22c7-4e14-89b2-d0d670628696"]
2024-02-29 02:48:36:425 [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s <device> shell settings get global wifi_on'
2024-02-29 02:48:36:485 [AndroidUiautomator2Driver@6a5b (415b5b17)] Turning WiFi off
2024-02-29 02:48:36:486 [ADB] Running 'C:\AndroidSDK\platform-tools\adb.exe -P 5037 -s <device> shell am broadcast -a io.appium.settings.wifi -n io.appium.settings/.receivers.WiFiConnectionSettingReceiver --es setstatus disable'
2024-02-29 02:48:36:558 [AndroidUiautomator2Driver@6a5b (415b5b17)] Responding to client with driver.toggleWiFi() result: null
2024-02-29 02:48:36:559 [HTTP] <-- POST /session/415b5b17-22c7-4e14-89b2-d0d670628696/appium/device/toggle_wifi 200 136 ms - 14



This is what I get when I run my code to toggle wifi.

**Comment by HarshdeepSingh3009** [comment]
This issue is resolved, Appium driver version being used was old, updated it to latest and it is working.. closing the issue. Thanks !
