### ISSUE TITLE
[Bug]: Android Device - adb.exe: error: cannot bind listener: cannot bind to 127.0.0.1:8200: An attempt was made to access a socket in a way forbidden by its access permissions. (10013)

### ISSUE THREAD

**Issue by MaximG1234** [appium/dotnet-client#819]
## Description

Hi, I am trying to configure a test project for Maui app. I want to test against a device (Galaxy A54).

I have the following code:

```
 var builder = new AppiumServiceBuilder();
 builder
     .WithIPAddress("127.0.0.1")
     .UsingPort(4723);

service = builder.Build();
service.Start();

if (!service.IsRunning)
    throw new Exception("Appium Local Service did not start");

var androidOptions = new AppiumOptions() 
{
    AutomationName = AutomationName.AndroidUIAutomator2,
    PlatformName = "Android"
}

androidOptions.AddAdditionalAppiumOption(MobileCapabilityType.NoReset, "true");
androidOptions.AddAdditionalAppiumOption(MobileCapabilityType.Udid, "my device id");
androidOptions.AddAdditionalAppiumOption(AndroidMobileCapabilityType.AppPackage, $"{my.app.name}");
androidOptions.AddAdditionalAppiumOption(AndroidMobileCapabilityType.AppActivity, $"{my.app.name}.MainActivity");

var driver = new AndroidDriver(service, androidOptions); //exception thrown here.

```

However I am getting the error:

**An unknown server-side error occurred while processing the command.** 

`Original error: Error executing adbExec. Original error: 'Command 'C:\\android-sdk\\platform-tools\\adb.exe -P 5037 -s mydeviceid forward tcp\:8200 tcp\:6790' exited with code 1'; Command output: adb.exe: error: cannot bind listener: cannot bind to 127.0.0.1:8200: An attempt was made to access a socket in a way forbidden by its access permissions. (10013)`

Anyone able to point me in the right direction? am I doing something wrong or could this be a bug?

## Environment

* .NET 8
* Appium server version or git revision if you use some snapshot:
* Desktop OS/version used to run Appium if necessary: Windows 10
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe:
* Mobile platform/version under test: Maui
* Real device or emulator/simulator: Real Device

## Exception stack traces

   ```
at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.<ExecuteAsync>d__63.MoveNext()
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Appium.AppiumDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.StartSession(ICapabilities capabilities)
   at OpenQA.Selenium.WebDriver..ctor(ICommandExecutor executor, ICapabilities capabilities)
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(ICommandExecutor commandExecutor, ICapabilities appiumOptions)
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(AppiumLocalService service, ICapabilities appiumOptions, TimeSpan commandTimeout, AppiumClientConfig clientConfig)
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(AppiumLocalService service, ICapabilities appiumOptions, TimeSpan commandTimeout)
   at OpenQA.Selenium.Appium.AppiumDriver..ctor(AppiumLocalService service, ICapabilities appiumOptions)
   at OpenQA.Selenium.Appium.Android.AndroidDriver..ctor(AppiumLocalService service, DriverOptions driverOptions)
```

Server:

```
Error: Command 'C:\\android-sdk\\platform-tools\\adb.exe -P 5037 -s deviceid forward tcp\:8200 tcp\:6790' exited with code 1
    at ChildProcess.<anonymous> (C:\Users\user\.appium\node_modules\appium-uiautomator2-driver\node_modules\teen_process\lib\exec.js:110:19)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:303:5)
    at Process.callbackTrampoline (node:internal/async_hooks:128:17)
[4291271a][HTTP] <-- POST /session 500 925 ms - 1274
```

**Comment by MaximG1234** [comment]
Ah, apologies looks like I worked out the problem. I needed to change the systemPort for the uiautomator. Not 100% sure why.


       ` androidOptions.AddAdditionalAppiumOption("systemPort", 8100);`
